version: "2"
linters:
  settings:
    staticcheck:
      dot-import-whitelist:
        - "github.com/volkszaehler/mbmd/meters"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: "`sunspecModelID` is unused"
      - path: (.+)\.go$
        text: "`printModel` is unused"
      - path: (.+)\.go$
        text: "func printModel is unused"
      - path: (.+)\.go$
        text: "func \\(\\*SunSpec\\).sanitizeModels is unused"
      - path: (.+)\.go$
        text: "func \\(\\*SunSpec\\).relevantModelIds is unused"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
