package meters

var SunspecModels = map[int]string{
	1: "Common",
	2: "Basic Aggregator",
	3: "Secure Dataset Read Request",
	4: "Secure Dataset Read Response",
	5: "Secure Write Request",
	6: "Secure Write Sequential Request",
	7: "Secure Write Response Model (DRAFT 1)",
	8: "Get Device Security Certificate",
	9: "Set Operator Security Certificate",
	10: "Communication Interface Header",
	11: "Ethernet Link Layer",
	12: "IPv4",
	13: "IPv6",
	14: "Proxy Server",
	15: "Interface Counters Model",
	16: "Simple IP Network",
	17: "Serial Interface",
	18: "Cellular Link",
	19: "PPP Link",
	101: "Inverter (Single Phase)",
	102: "Inverter (Split-Phase)",
	103: "Inverter (Three Phase)",
	111: "Inverter (Single Phase) FLOAT",
	112: "Inverter (Split Phase) FLOAT",
	113: "Inverter (Three Phase) FLOAT",
	120: "Nameplate",
	121: "Basic Settings",
	122: "Measurements_Status",
	123: "Immediate Controls",
	124: "Storage",
	125: "Pricing",
	126: "Static Volt-VAR",
	127: "Freq-Watt Param",
	128: "Dynamic Reactive Current",
	129: "LVRTD",
	130: "HVRTD",
	131: "Watt-PF",
	132: "Volt-Watt",
	133: "Basic Scheduling",
	134: "Freq-Watt Crv",
	135: "LFRT",
	136: "HFRT",
	137: "LVRTC",
	138: "HVRTC",
	139: "LVRTX",
	140: "HVRTX",
	141: "LFRTC",
	142: "HFRTC",
	143: "LFRTX",
	144: "HFRTX",
	145: "Extended Settings",
	160: "Multiple MPPT Inverter Extension Model",
	201: "Meter (Single Phase)single phase (AN or AB) meter",
	202: "split single phase (ABN) meter",
	203: "wye-connect three phase (abcn) meter",
	204: "delta-connect three phase (abc) meter",
	211: "single phase (AN or AB) meter",
	212: "split single phase (ABN) meter",
	213: "wye-connect three phase (abcn) meter",
	214: "delta-connect three phase (abc) meter",
	220: "Secure AC Meter Selected Readings",
	302: "Irradiance Model",
	303: "Back of Module Temperature Model",
	304: "Inclinometer Model",
	305: "GPS",
	306: "Reference Point Model",
	307: "Base Met",
	308: "Mini Met Model",
	401: "String Combiner (Current)",
	402: "String Combiner (Advanced)",
	403: "String Combiner (Current)",
	404: "String Combiner (Advanced)",
	501: "Solar Module",
	502: "Solar Module",
	601: "Tracker Controller DRAFT 2",
	801: "Energy Storage Base Model (DEPRECATED)",
	802: "Battery Base Model",
	803: "Lithium-Ion Battery Bank Model",
	804: "Lithium-Ion String Model",
	805: "Lithium-Ion Module Model",
	806: "Flow Battery Model",
	807: "Flow Battery String Model",
	808: "Flow Battery Module Model",
	809: "Flow Battery Stack Model",
	63001: "SunSpec Test Model 1",
	63002: "SunSpec Test Model 2",
	64001: "Veris Status and Configuration",
	64020: "Mersen GreenString",
	64101: "Eltek Inverter Extension",
	64110: "OutBack AXS device",
	64111: "Basic Charge Controller",
	64112: "OutBack FM Charge Controller",
}
