// Code generated by "enumer -type=Unit -transform=snake"; DO NOT EDIT.

//
package meters

import (
	"fmt"
)

const _UnitName = "kilo_var_hourvarkilo_watt_hourwattamperevoltvolt_amperedegreedegree_celsiushertzpercentno_unit"

var _UnitIndex = [...]uint8{0, 13, 16, 30, 34, 40, 44, 55, 61, 75, 80, 87, 94}

func (i Unit) String() string {
	i -= 1
	if i < 0 || i >= Unit(len(_UnitIndex)-1) {
		return fmt.Sprintf("Unit(%d)", i+1)
	}
	return _UnitName[_UnitIndex[i]:_UnitIndex[i+1]]
}

var _UnitValues = []Unit{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

var _UnitNameToValueMap = map[string]Unit{
	_UnitName[0:13]:  1,
	_UnitName[13:16]: 2,
	_UnitName[16:30]: 3,
	_UnitName[30:34]: 4,
	_UnitName[34:40]: 5,
	_UnitName[40:44]: 6,
	_UnitName[44:55]: 7,
	_UnitName[55:61]: 8,
	_UnitName[61:75]: 9,
	_UnitName[75:80]: 10,
	_UnitName[80:87]: 11,
	_UnitName[87:94]: 12,
}

// UnitString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UnitString(s string) (Unit, error) {
	if val, ok := _UnitNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Unit values", s)
}

// UnitValues returns all values of the enum
func UnitValues() []Unit {
	return _UnitValues
}

// IsAUnit returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Unit) IsAUnit() bool {
	for _, v := range _UnitValues {
		if i == v {
			return true
		}
	}
	return false
}
