// Code generated by "stringer -type=Measurement"; DO NOT EDIT.

package meters

import "strconv"

const _Measurement_name = "SplitVoltageL1VoltageL2VoltageL3CurrentL1CurrentL2CurrentL3PowerL1PowerL2PowerL3ActivePowerL1ReactivePowerL1ApparentPowerL1ActivePowerL2ReactivePowerL2ApparentPowerL2ActivePowerL3ReactivePowerL3ApparentPowerL3ImportL1ImportL2ImportL3ExportL1ExportL2ExportL3PowerFactorL1PowerFactorL2PowerFactorL3CosphiL1CosphiL2CosphiL3THDL1THDL2THDL3VoltageCurrentPowerActivePowerReactivePowerApparentPowerPowerFactorCosphiTHDFrequencyNetNetL1NetL2NetL3ActiveActiveNetActiveNetL1ActiveNetL2ActiveNetL3ReactiveReactiveNetReactiveNetL1ReactiveNetL2ReactiveNetL3ImportExportActiveImportT1ActiveImportT2ReactiveImportT1ReactiveImportT2ActiveExportT1ActiveExportT2ReactiveExportT1ReactiveExportT2DCCurrentDCVoltageDCPowerHeatSinkTemp"

var _Measurement_index = [...]uint16{0, 5, 14, 23, 32, 41, 50, 59, 66, 73, 80, 93, 108, 123, 136, 151, 166, 179, 194, 209, 217, 225, 233, 241, 249, 257, 270, 283, 296, 304, 312, 320, 325, 330, 335, 342, 349, 354, 365, 378, 391, 402, 408, 411, 420, 423, 428, 433, 438, 444, 453, 464, 475, 486, 494, 505, 518, 531, 544, 550, 556, 570, 584, 600, 616, 630, 644, 660, 676, 685, 694, 701, 713}

func (i Measurement) String() string {
	if i < 0 || i >= Measurement(len(_Measurement_index)-1) {
		return "Measurement(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Measurement_name[_Measurement_index[i]:_Measurement_index[i+1]]
}
